# single test suite, non-parallel build.

env:
  global:
    - CC_TEST_REPORTER_ID=e87f16b9111405bdb1c8e94f120487caccba356eed4f14c8d161e56b66faf0bc
language: ruby
rvm:
  - 2.5.0
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
cache:
  - bundler
script:
  - bundle install && bin/rails db:create && bin/rails db:migrate && bundle exec rspec
services:
  - postgresql
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
